* ZOOM-TO-POINT

This is not an Emacs ``mode" so much as a few convenient function
definitions and a slightly less convenient variable declaration.

That said, the functions at least do pretty much what they say:
namely, they zoom towards and away from the point using the specified ``level" of
zoom you require, with the now-larger or -smaller text centered in the
buffer.

Specify the zoom-level in the parameter =*default-zoom-level*=. For now, type

#+BEGIN_SRC emacs-lisp
  (defvar *default-zoom-level* 3)
#+END_SRC

into the =*scratch*= buffer and evaluate it.

Then zoom in on whatever you're aimed at with

#+BEGIN_EXAMPLE
M-x zoom-to-point
#+END_EXAMPLE

To return to your default code- or text-viewing experience, use

#+BEGIN_EXAMPLE
M-x unzoom
#+END_EXAMPLE

to return to your standard font size.

Alternatively, the function =zoom-toggle= is defined, which will check
if you are currently ``zoomed," and then call =zoom-to-point= or =unzoom= as
appropriate. You can bind it to a single key chord in your =.emacs=
file for ease of use,
e.g.,

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c z") 'zoom-toggle)
#+END_SRC

This interface is clunky and represents a minimal early working
version. Expect changes, or better yet, contribute some!
